const actionTypes = {
    LOAD_PHOTOS_REQUEST: 'LOAD_PHOTOS_REQUEST',
    LOAD_PHOTOS_SUCCESS: 'LOAD_PHOTOS_SUCCESS',
    LOAD_PHOTOS_ERROR: 'LOAD_PHOTOS_ERROR',
    LOAD_PHOTOGRAPHERS_REQUEST: 'LOAD_PHOTOGRAPHERS_REQUEST',
    LOAD_PHOTOGRAPHERS_SUCCESS: 'LOAD_PHOTOGRAPHERS_SUCCESS',
    LOAD_PHOTOGRAPHERS_ERROR: 'LOAD_PHOTOGRAPHERS_ERROR',
    LOAD_PHOTOGRAPHER_REQUEST: 'LOAD_PHOTOGRAPHER_REQUEST',
    LOAD_PHOTOGRAPHER_SUCCESS: 'LOAD_PHOTOGRAPHER_SUCCESS',
    LOAD_PHOTOGRAPHER_ERROR: 'LOAD_PHOTOGRAPHER_ERROR',
    LOAD_PHOTO_REQUEST: 'LOAD_PHOTO_REQUEST',
    LOAD_PHOTO_SUCCESS: 'LOAD_PHOTO_SUCCESS',
    LOAD_PHOTO_ERROR: 'LOAD_PHOTO_ERROR',
    LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_ERROR: 'LOGIN_USER_ERROR'
};

export default actionTypes;
